version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.22.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres  # 数据库类型
      - GITEA__database__HOST=host.docker.internal:5432 # 链接地址
      - GITEA__database__NAME=gitea # 数据库名
      - GITEA__database__USER=gitea # 数据库账号
      - GITEA__database__PASSWD=gitea #数据库密码
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "222:22"
